#!/usr/bin/env python3
"""self_loop.py (s180) — pure Python orchestrator (bash blocked by TCC)."""
import subprocess, sys, datetime
from pathlib import Path
ROOT = Path.home() / "Desktop" / "ai-hub"
LOG = ROOT / "self/curator/self_loop.log"
STATUS = ROOT / "self/curator/STATUS.md"
REPORT = ROOT / "self/curator/SELF_RESEARCH_REPORT.md"
PY = sys.executable

def log(m):
    with LOG.open("a", encoding="utf-8") as f:
        f.write(m + "\n")

def run(args, timeout=900):
    try:
        r = subprocess.run(args, cwd=str(ROOT), capture_output=True,
                           text=True, timeout=timeout)
        log(f"rc={r.returncode} cmd={' '.join(args[-3:])}")
        if r.stdout: log("OUT: " + r.stdout[-1500:])
        if r.stderr: log("ERR: " + r.stderr[-1500:])
        return r.returncode
    except Exception as e:
        log(f"FAILED: {e!r}")
        return 1

def wc(p):
    try: return sum(1 for _ in p.open())
    except: return 0

log(f"=== cycle start {datetime.datetime.now()} ===")
run([PY, str(ROOT/"scripts/research/self_research.py"), "--run", "--limit", "2"])
run([PY, str(ROOT/"scripts/autonomous_apply.py"), "--classify"], timeout=300)

now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
L = [
    "# STATUS (auto-generated by self_loop.py)",
    f"**Updated:** {now}",
    "",
    "## Counters",
    f"- PROPOSALS.jsonl: **{wc(ROOT/'self/curator/PROPOSALS.jsonl')}**",
    f"- SELF_PROPOSALS.jsonl: **{wc(ROOT/'self/curator/SELF_PROPOSALS.jsonl')}**",
    "",
    "## Last research report",
    "",
]
L.append(REPORT.read_text(encoding="utf-8")[-2000:] if REPORT.exists() else "(no report yet)")
L += ["", "---", "Full log: `self/curator/self_loop.log`"]
STATUS.write_text("\n".join(L) + "\n", encoding="utf-8")
log(f"=== cycle done {datetime.datetime.now()} ===")
