#!/bin/bash
cd /Users/salamkhalikov/Desktop/ai-hub
LOG="self/curator/self_loop.log"
STATUS="self/curator/STATUS.md"
{
echo "=== cycle start $(date '+%F %T') ==="
/usr/bin/python3 scripts/research/self_research.py --run --limit 2 >> "$LOG" 2>&1
echo "--- research done, classify ---"
/usr/bin/python3 scripts/autonomous_apply.py --classify >> "$LOG" 2>&1 || true
echo "--- classify done, report ---"
} >> "$LOG" 2>&1

python3 - << 'PYINNER'
import json, pathlib, datetime
ROOT = pathlib.Path("/Users/salamkhalikov/Desktop/ai-hub")
p = ROOT / "self/curator/PROPOSALS.jsonl"
sp = ROOT / "self/curator/SELF_PROPOSALS.jsonl"
rep = ROOT / "self/curator/SELF_RESEARCH_REPORT.md"
status = ROOT / "self/curator/STATUS.md"
def wc(f):
    try: return sum(1 for _ in f.open())
    except: return 0
now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
lines = [
    "# STATUS (auto-generated by self_loop.sh)",
    "",
    "**Updated:** " + now,
    "",
    "## Counters",
    "- PROPOSALS.jsonl: **" + str(wc(p)) + "**",
    "- SELF_PROPOSALS.jsonl: **" + str(wc(sp)) + "**",
    "",
    "## Last research report",
    "",
]
if rep.exists():
    lines.append(rep.read_text(encoding="utf-8")[-1500:])
else:
    lines.append("(no report yet)")
lines.append("")
lines.append("---")
lines.append("Full log: `self/curator/self_loop.log`")
status.write_text("\n".join(lines), encoding="utf-8")
PYINNER
